[package]
name = "monopoly-math"
version = "0.1.0"
authors = ["Haziq Hairil <haziqhairil21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.0"